name: Ziggeo Release build
on:
  push:
    branches: [ 'feature_build_cicd' ]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: '>> Dart package <<'
        uses: k-paxian/dart-package-publisher@master
        with:
            accessToken: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
            refreshToken: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}


#
#      - name: "Setup Pub Credentials"
#        shell: bash
#        env:
#          PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
#          PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
#          PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
#          PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
#        run: |
#          sh ./pub_login.sh
#      - name: "Check Flutter Release Version"
#        run: |
#          flutter pub publish --dry-run
#
#      - name: "Run Flutter Release Publish"
#        run: |
#          flutter pub publish -f

